# SPDX-License-Identifier: GPL-2.0-or-later
#
# Single source of truth for UniLume version numbers.
# Include via include(UniLumeVersion) after project().
#
# Provided variables:
#   UNILUME_VERSION_MAJOR
#   UNILUME_VERSION_MINOR
#   UNILUME_VERSION_PATCH
#   UNILUME_VERSION_TWEAK    (empty for stable)
#   UNILUME_VERSION_IS_PRERELEASE  (TRUE/FALSE)
#   UNILUME_VERSION_STRING   e.g. "0.1.0-rc.1"
#   UNILUME_VERSION_SEMVER   e.g. "0.1.0-rc.1"
#   UNILUME_DEBIAN_VERSION   e.g. "0.1.0~rc1"
#   UNILUME_RPM_VERSION      e.g. "0.1.0"
#   UNILUME_RPM_RELEASE      e.g. "0.rc1.1"
#   UNILUME_ARCH_VERSION     e.g. "0.1.0rc1"

if(UNILUME_VERSION_INCLUDED)
  return()
endif()
set(UNILUME_VERSION_INCLUDED TRUE)

# ---- Edit here for each release ----
set(UNILUME_VERSION_MAJOR 0)
set(UNILUME_VERSION_MINOR 1)
set(UNILUME_VERSION_PATCH 0)
set(UNILUME_VERSION_TWEAK "")   # empty for stable; e.g. "rc1", "rc2"

# ---- Derived ----
if(UNILUME_VERSION_TWEAK STREQUAL "")
  set(UNILUME_VERSION_IS_PRERELEASE FALSE)
  set(UNILUME_VERSION_STRING "${UNILUME_VERSION_MAJOR}.${UNILUME_VERSION_MINOR}.${UNILUME_VERSION_PATCH}")
  set(UNILUME_VERSION_SEMVER  "${UNILUME_VERSION_MAJOR}.${UNILUME_VERSION_MINOR}.${UNILUME_VERSION_PATCH}")
  set(UNILUME_DEBIAN_VERSION  "${UNILUME_VERSION_MAJOR}.${UNILUME_VERSION_MINOR}.${UNILUME_VERSION_PATCH}")
  set(UNILUME_RPM_VERSION     "${UNILUME_VERSION_MAJOR}.${UNILUME_VERSION_MINOR}.${UNILUME_VERSION_PATCH}")
  set(UNILUME_RPM_RELEASE     "1")
  set(UNILUME_ARCH_VERSION    "${UNILUME_VERSION_MAJOR}.${UNILUME_VERSION_MINOR}.${UNILUME_VERSION_PATCH}")
else()
  set(UNILUME_VERSION_IS_PRERELEASE TRUE)
  set(UNILUME_VERSION_STRING "${UNILUME_VERSION_MAJOR}.${UNILUME_VERSION_MINOR}.${UNILUME_VERSION_PATCH}-${UNILUME_VERSION_TWEAK}")
  set(UNILUME_VERSION_SEMVER  "${UNILUME_VERSION_MAJOR}.${UNILUME_VERSION_MINOR}.${UNILUME_VERSION_PATCH}-${UNILUME_VERSION_TWEAK}")
  set(UNILUME_DEBIAN_VERSION  "${UNILUME_VERSION_MAJOR}.${UNILUME_VERSION_MINOR}.${UNILUME_VERSION_PATCH}~${UNILUME_VERSION_TWEAK}")
  set(UNILUME_RPM_VERSION     "${UNILUME_VERSION_MAJOR}.${UNILUME_VERSION_MINOR}.${UNILUME_VERSION_PATCH}")
  set(UNILUME_RPM_RELEASE     "0.${UNILUME_VERSION_TWEAK}.1")
  set(UNILUME_ARCH_VERSION    "${UNILUME_VERSION_MAJOR}.${UNILUME_VERSION_MINOR}.${UNILUME_VERSION_PATCH}${UNILUME_VERSION_TWEAK}")
endif()

message(STATUS "UniLume version: ${UNILUME_VERSION_STRING}")
